### ISSUE TITLE
Fixing the MessageMover

### ISSUE THREAD

**Issue by GamerDude27** [BeepFelix/Concepts#1]
https://github.com/BeepFelix/Concepts/blob/3eb20a3a338298dc5f0f963f80474c77a551c886/discord-messagemover/_.messagemover.js#L57
This line will return the error `fromChannel.messages.fetch is not a function`, to fix it replace `channel.messages.fetch` with `channel.fetchMessage`

https://github.com/BeepFelix/Concepts/blob/3eb20a3a338298dc5f0f963f80474c77a551c886/discord-messagemover/_.messagemover.js#L62
Specifically `avatarURL: message.author.avatarURL()`. `avatarURL()` on stable 11.5.1 is a property, not a function. So just remove the `()` and you're good to go.

Hope this helps!

**Comment by BeepFelix** [comment]
I am not actively maintaining this.

These are all written in a kinda old Discord.JS Master version, the message mover you pointed out seems to still be correct though as per Discord.JS master docs.
